
import React, { useState, useMemo } from 'react';
import { useAppContext } from '../context/AppContext';
import { useVertical } from '../hooks/useVertical';
import { ItemStatus, JobStatus, TransactionType, Kit, InventoryItem } from '../types';
import { ArrowLeft, Edit, Trash2, CheckSquare, Square, FileSignature, X, Clock, User as UserIcon, FileText, Download, Weight, Receipt, Plus, DollarSign } from 'lucide-react';
import ConfirmModal from '../components/ConfirmModal';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const JobDetailScreen: React.FC<{ jobId: number }> = ({ jobId }) => {
  const { state, navigateTo, findJob, findItem, findUser, deleteJob } = useAppContext();
  const { t } = useVertical();
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [selectedItemIds, setSelectedItemIds] = useState<number[]>([]);
  
  // Signature Modal State
  const [viewSignature, setViewSignature] = useState<string | null>(null);

  const job = findJob(jobId);

  if (!job) {
    return <div className="text-slate-900 dark:text-white">{t.job} not found.</div>;
  }
  
  const producer = findUser(job.producerId);

  // Get Transactions for this job (sorted newest first)
  const jobTransactions = state.transactions
    .filter(t => t.jobId === jobId)
    .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

  // Get Receipts for this job
  const jobReceipts = state.receipts
    .filter(r => r.job_id === jobId)
    .sort((a, b) => new Date(b.expense_date).getTime() - new Date(a.expense_date).getTime());

  const totalExpenses = jobReceipts.reduce((sum, r) => sum + r.amount, 0);

  const checkedOutItems = state.inventory
      .filter(item => item.status === ItemStatus.CHECKED_OUT &&
                      item.history.length > 0 &&
                      item.history[0].jobId === jobId)
      .length;

  const totalItems = job.gearList.length;

  // Helper to get who has an item checked out
  const getCheckedOutTo = (item: typeof state.inventory[0]): string | null => {
      if (item.status !== ItemStatus.CHECKED_OUT || !item.history || item.history.length === 0) return null;
      const lastCheckout = item.history[0];
      return lastCheckout.assignedToName || (lastCheckout.assignedToId ? findUser(lastCheckout.assignedToId)?.name : null) || (findUser(lastCheckout.userId)?.name) || null;
  };

  // Calculate Total Job Weight
  const totalJobWeight = job.gearList.reduce((sum, entry) => {
      const item = findItem(entry.itemId);
      return sum + (item?.weight || 0);
  }, 0);

  // Filter items by status
  const availableForCheckout = useMemo(() => {
      return job.gearList
          .map(g => findItem(g.itemId))
          .filter(i => i && i.status === ItemStatus.AVAILABLE)
          .map(i => i!.id);
  }, [job.gearList, state.inventory]);

  const checkedOutItemIds = useMemo(() => {
      return job.gearList
          .map(g => findItem(g.itemId))
          .filter(i => i && i.status === ItemStatus.CHECKED_OUT)
          .map(i => i!.id);
  }, [job.gearList, state.inventory]);

  const allItemIds = useMemo(() => {
      return job.gearList.map(g => g.itemId);
  }, [job.gearList]);

  const handleSelectAll = () => {
      if (selectedItemIds.length === allItemIds.length) {
          setSelectedItemIds([]);
      } else {
          setSelectedItemIds([...allItemIds]);
      }
  };

  const toggleSelection = (itemId: number) => {
      setSelectedItemIds(prev =>
          prev.includes(itemId)
              ? prev.filter(id => id !== itemId)
              : [...prev, itemId]
      );
  };

  // Split selection by status
  const selectedAvailable = selectedItemIds.filter(id => availableForCheckout.includes(id));
  const selectedCheckedOut = selectedItemIds.filter(id => checkedOutItemIds.includes(id));

  const handleCheckout = () => {
      navigateTo('CHECKOUT', {
          jobId: job.id,
          preSelectedIds: selectedAvailable
      });
  };

  const handleCheckin = () => {
      navigateTo('CHECKIN', { jobId: job.id });
  };

  const handleDelete = async () => {
      await deleteJob(job.id);
      navigateTo('JOB_LIST');
  };

  const generateManifest = async () => {
      try {
          const { addLogoToDoc } = await import('../lib/pdfLogo');
          const doc = new jsPDF();

          // --- Logo ---
          await addLogoToDoc(doc, state.orgLogoUrl);

          // --- Header ---
          doc.setFontSize(22);
          doc.setTextColor(40, 40, 40);
          doc.text("EQUIPMENT MANIFEST", 14, 20);

          doc.setFontSize(10);
          doc.setTextColor(80, 80, 80);
          doc.text("Generated by Gear Base", 14, 26);

          // --- Job Details Box ---
          doc.setDrawColor(200, 200, 200);
          doc.setFillColor(245, 245, 245);
          doc.rect(14, 32, 182, 36, 'F'); // Increased height for weight info
          
          doc.setFontSize(14);
          doc.setTextColor(0, 0, 0);
          doc.text(job.name, 20, 42);

          // Helper to format time (e.g., "17:00" -> "5:00 PM")
          const formatTime = (time: string | undefined) => {
              if (!time) return null;
              const [hours, minutes] = time.split(':').map(Number);
              const ampm = hours >= 12 ? 'PM' : 'AM';
              const hour12 = hours % 12 || 12;
              return `${hour12}:${minutes.toString().padStart(2, '0')} ${ampm}`;
          };

          doc.setFontSize(10);
          doc.text(`Dates: ${new Date(job.startDate).toLocaleDateString()} - ${new Date(job.endDate).toLocaleDateString()}`, 20, 50);

          // Build times string
          const soundCheck = formatTime(job.soundCheckTime);
          const startTime = formatTime(job.startTime);
          let timesLine = '';
          if (soundCheck) timesLine += `Sound Check: ${soundCheck}`;
          if (soundCheck && startTime) timesLine += '  |  ';
          if (startTime) timesLine += `Start: ${startTime}`;
          if (timesLine) {
              doc.text(timesLine, 20, 56);
              doc.text(`${t.producer}: ${producer?.name || 'Unknown'}`, 20, 62);
          } else {
              doc.text(`${t.producer}: ${producer?.name || 'Unknown'}`, 20, 56);
          }

          doc.text(`Total Items: ${totalItems}`, 140, 50);
          doc.text(`Total Weight: ${totalJobWeight.toFixed(1)} lbs`, 140, 56);
          doc.text(`Status: ${job.status}`, 140, 62);

          // --- Gear List Table (grouped by package) ---
          // 1. Get Items
          const items = job.gearList
              .map(g => findItem(g.itemId))
              .filter(i => i !== undefined);

          // 2. Group items by kit membership
          const jobItemIds = new Set(items.map(i => i!.id));
          const kitGroups: { kit: Kit; items: InventoryItem[] }[] = [];
          const itemsInKits = new Set<number>();

          // Find kits that have items in this job
          state.kits.forEach(kit => {
              const kitItemsInJob = kit.itemIds
                  .filter(id => jobItemIds.has(id))
                  .map(id => items.find(i => i!.id === id)!)
                  .filter(Boolean);
              // Only show as a kit group if at least 2 kit items are in the job
              if (kitItemsInJob.length >= 2) {
                  kitGroups.push({ kit, items: kitItemsInJob });
                  kitItemsInJob.forEach(i => itemsInKits.add(i.id));
              }
          });

          // Loose items not in any kit
          const looseItems = items.filter(i => !itemsInKits.has(i!.id));

          // Sort kit groups by name, items within each group by category then name
          kitGroups.sort((a, b) => a.kit.name.localeCompare(b.kit.name));
          const sortItems = (arr: InventoryItem[]) => arr.sort((a, b) => {
              if (a.category < b.category) return -1;
              if (a.category > b.category) return 1;
              return a.name.localeCompare(b.name);
          });

          let startY = 75;

          // Render each kit group as a separate table section
          kitGroups.forEach(({ kit, items: kitItems }) => {
              sortItems(kitItems);
              const kitWeight = kitItems.reduce((sum, i) => sum + (i.weight || 0), 0);

              // Kit header
              doc.setFontSize(11);
              doc.setTextColor(0, 0, 0);
              doc.setFont(undefined as any, 'bold');
              doc.text(`${kit.name}  (${kitItems.length} items, ${kitWeight.toFixed(1)} lbs)`, 14, startY);
              doc.setFont(undefined as any, 'normal');
              startY += 2;

              autoTable(doc, {
                  startY,
                  head: [['[ ]', 'Qty', 'Item Name', 'Category', 'Case/Bin', 'Weight', 'Serial/QR', 'Status']],
                  body: kitItems.map(item => [
                      '', '1', item.name, item.category,
                      item.storageCase || '-',
                      item.weight ? `${item.weight} lbs` : '-',
                      item.qrCode || '-',
                      item.status === ItemStatus.CHECKED_OUT ? 'Out' : ''
                  ]),
                  theme: 'grid' as const,
                  headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255], fontStyle: 'bold' as const },
                  alternateRowStyles: { fillColor: [245, 245, 245] },
                  columnStyles: {
                      0: { cellWidth: 10, halign: 'center' as const },
                      1: { cellWidth: 14, halign: 'center' as const },
                      5: { halign: 'right' as const },
                      7: { fontStyle: 'bold' as const }
                  },
                  styles: { fontSize: 9, cellPadding: 3, lineColor: [200, 200, 200], lineWidth: 0.25 }
              });
              startY = (doc as any).lastAutoTable.finalY + 10;
              if (startY > 260) { doc.addPage(); startY = 20; }
          });

          // Loose items (not in any package)
          if (looseItems.length > 0) {
              sortItems(looseItems as InventoryItem[]);

              if (kitGroups.length > 0) {
                  doc.setFontSize(11);
                  doc.setTextColor(0, 0, 0);
                  doc.setFont(undefined as any, 'bold');
                  doc.text(`Other Items  (${looseItems.length})`, 14, startY);
                  doc.setFont(undefined as any, 'normal');
                  startY += 2;
              }

              autoTable(doc, {
                  startY,
                  head: [['[ ]', 'Qty', 'Item Name', 'Category', 'Case/Bin', 'Weight', 'Serial/QR', 'Status']],
                  body: looseItems.map(item => [
                      '', '1', item!.name, item!.category,
                      item!.storageCase || '-',
                      item!.weight ? `${item!.weight} lbs` : '-',
                      item!.qrCode || '-',
                      item!.status === ItemStatus.CHECKED_OUT ? 'Out' : ''
                  ]),
                  theme: 'grid' as const,
                  headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255], fontStyle: 'bold' as const },
                  alternateRowStyles: { fillColor: [245, 245, 245] },
                  columnStyles: {
                      0: { cellWidth: 10, halign: 'center' as const },
                      1: { cellWidth: 14, halign: 'center' as const },
                      5: { halign: 'right' as const },
                      7: { fontStyle: 'bold' as const }
                  },
                  styles: { fontSize: 9, cellPadding: 3, lineColor: [200, 200, 200], lineWidth: 0.25 }
              });
          }

          // --- Footer Signatures ---
          // @ts-ignore - autoTable adds lastAutoTable to doc object
          let finalY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 30 : 150;
          
          // Check if we need a new page for signatures
          if (finalY > 250) {
              doc.addPage();
              finalY = 40;
          }

          doc.setDrawColor(0, 0, 0);
          doc.line(20, finalY, 90, finalY); // Line 1
          doc.line(120, finalY, 190, finalY); // Line 2
          
          doc.setFontSize(10);
          doc.text("Prepped By / Date", 20, finalY + 5);
          doc.text("Received By / Date", 120, finalY + 5);

          // Save
          doc.save(`Manifest - ${job.name}.pdf`);
      } catch (err: any) {
          console.error("PDF Generation Error:", err);
          alert("Failed to generate PDF. Please ensure you are using a modern browser. Error: " + err.message);
      }
  };

  return (
    <div className="pb-20">
      <ConfirmModal 
        isOpen={showDeleteModal}
        title={`Delete ${t.job}`}
        message={`Are you sure you want to delete "${job.name}"? This will permanently remove the ${t.job.toLowerCase()} and its history.`}
        confirmText={`Delete ${t.job}`}
        isDestructive={true}
        onConfirm={handleDelete}
        onCancel={() => setShowDeleteModal(false)}
      />

      {/* SIGNATURE MODAL */}
      {viewSignature && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in">
              <div className="bg-white dark:bg-slate-800 w-full max-w-lg rounded-lg shadow-2xl overflow-hidden border border-slate-200 dark:border-slate-700">
                  <div className="p-4 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center bg-slate-50 dark:bg-slate-900">
                      <h3 className="font-bold text-slate-900 dark:text-white flex items-center gap-2">
                          <FileSignature className="text-sky-500" /> Digital Signature
                      </h3>
                      <button onClick={() => setViewSignature(null)} className="text-slate-500 hover:text-slate-900 dark:hover:text-white">
                          <X size={20} />
                      </button>
                  </div>
                  <div className="p-6 flex justify-center bg-slate-900">
                      {/* Signature is white-ink transparent PNG, so we need a dark background */}
                      <img src={viewSignature} alt="Signature" className="max-w-full h-auto border border-slate-700 rounded bg-slate-800/50" />
                  </div>
                  <div className="p-4 bg-slate-50 dark:bg-slate-900 text-center">
                      <button 
                          onClick={() => setViewSignature(null)}
                          className="px-6 py-2 bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-800 dark:text-white font-bold rounded-lg transition-colors"
                      >
                          Close
                      </button>
                  </div>
              </div>
          </div>
      )}

      <div className="flex justify-between items-center mb-4">
        <button 
          onClick={() => navigateTo('JOB_LIST')}
          className="flex items-center gap-2 text-sm text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300 transition-colors font-semibold"
        >
          <ArrowLeft size={16} />
          Back to {t.jobPlural} List
        </button>
        <div className="flex gap-2">
            <button 
                onClick={generateManifest}
                className="hidden sm:flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300 hover:text-sky-600 dark:hover:text-sky-400 transition-colors font-semibold px-3 py-1 rounded hover:bg-slate-100 dark:hover:bg-slate-700"
            >
                <FileText size={16} />
                Manifest PDF
            </button>
            <button 
                onClick={() => setShowDeleteModal(true)}
                className="flex items-center gap-2 text-sm text-red-600 dark:text-red-400 hover:text-red-500 dark:hover:text-red-300 transition-colors font-semibold px-3 py-1 rounded hover:bg-red-100 dark:hover:bg-red-500/10"
            >
                <Trash2 size={16} />
                Delete {t.job}
            </button>
            <button
                onClick={() => navigateTo('EDIT_JOB', { jobId: job.id })}
                className="flex items-center gap-2 text-sm text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300 transition-colors font-semibold px-3 py-1 rounded hover:bg-sky-100 dark:hover:bg-sky-500/10"
            >
                <Edit size={16} />
                Edit {t.job}
            </button>
        </div>
      </div>

      <div className="space-y-6">
        <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">
          <div>
            <h2 className="text-3xl font-bold text-slate-900 dark:text-white">{job.name}</h2>
            <div className="flex flex-wrap items-center gap-3 mt-2 text-sm text-slate-600 dark:text-slate-400">
                <span>{new Date(job.startDate).toLocaleDateString()} - {new Date(job.endDate).toLocaleDateString()}</span>
                <span className="hidden sm:inline text-slate-300 dark:text-slate-600">|</span>
                <span>{t.producer}: {producer?.name}</span>
                <span className="hidden sm:inline text-slate-300 dark:text-slate-600">|</span>
                <span className="flex items-center gap-1 font-medium text-slate-800 dark:text-slate-200 bg-slate-100 dark:bg-slate-700/50 px-2 py-0.5 rounded">
                    <Weight size={14} className="text-slate-500 dark:text-slate-400" />
                    {totalJobWeight.toFixed(1)} lbs
                </span>
            </div>
          </div>
          
          {/* Mobile Manifest Button */}
          <button 
              onClick={generateManifest} 
              className="md:hidden w-full bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-white font-bold py-2 px-4 rounded-lg flex items-center justify-center gap-2"
          >
              <Download size={18}/> Download Manifest
          </button>

          <div className="mt-4 md:mt-0 flex gap-4">
              <button
                  onClick={handleCheckout}
                  className="bg-amber-500 hover:bg-amber-600 text-white font-bold py-2 px-6 rounded-lg transition-colors disabled:bg-slate-300 dark:disabled:bg-slate-600 disabled:cursor-not-allowed shadow-sm flex items-center gap-2"
                  disabled={(job.status !== JobStatus.UPCOMING && job.status !== JobStatus.IN_PROGRESS) || selectedAvailable.length === 0}
              >
                  Check-Out {selectedAvailable.length > 0 ? `(${selectedAvailable.length})` : ''}
              </button>
              <button
                  onClick={handleCheckin}
                  className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-6 rounded-lg transition-colors disabled:bg-slate-300 dark:disabled:bg-slate-600 disabled:cursor-not-allowed shadow-sm"
                  disabled={checkedOutItemIds.length === 0}
              >
                  Check-In {selectedCheckedOut.length > 0 ? `(${selectedCheckedOut.length})` : ''}
              </button>
          </div>
        </div>
        
        {/* GEAR LIST */}
        <div className="bg-white dark:bg-slate-800 rounded-lg p-6 shadow-lg border border-slate-200 dark:border-slate-700">
          <div className="flex justify-between items-center mb-4">
              <h3 className="text-xl font-semibold text-slate-900 dark:text-white">Gear List ({checkedOutItems}/{totalItems} Out)</h3>
              <button
                  onClick={handleSelectAll}
                  className="text-sm font-medium text-sky-600 dark:text-sky-400 hover:text-sky-700 dark:hover:text-sky-300 flex items-center gap-1"
              >
                  {selectedItemIds.length === allItemIds.length && allItemIds.length > 0 ? <CheckSquare size={16}/> : <Square size={16}/>}
                  Select All
              </button>
          </div>
          
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-700">
              <thead className="bg-slate-50 dark:bg-slate-900/50">
                <tr>
                  <th scope="col" className="w-10 px-6 py-3">
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Name</th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Category</th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Case/Bin</th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Status</th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Checked Out To</th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Condition</th>
                </tr>
              </thead>
              <tbody className="bg-white dark:bg-slate-800 divide-y divide-slate-200 dark:divide-slate-700">
                {job.gearList.map(({ itemId }) => {
                  const item = findItem(itemId);
                  if (!item) return null;

                  const isAvailable = item.status === ItemStatus.AVAILABLE;
                  const isSelected = selectedItemIds.includes(item.id);
                  const checkedOutTo = getCheckedOutTo(item);

                  return (
                    <tr
                        key={item.id}
                        className={`hover:bg-slate-50 dark:hover:bg-slate-700/50 cursor-pointer ${isSelected ? 'bg-sky-50 dark:bg-sky-900/10' : ''}`}
                        onClick={() => toggleSelection(item.id)}
                    >
                      <td className="px-6 py-4 whitespace-nowrap">
                          <div
                             onClick={(e) => { e.stopPropagation(); toggleSelection(item.id); }}
                             className={`w-5 h-5 rounded border flex items-center justify-center transition-colors cursor-pointer ${
                                 isSelected
                                    ? 'bg-sky-500 border-sky-500 text-white'
                                    : 'border-slate-300 dark:border-slate-500 bg-white dark:bg-slate-800'
                             }`}
                          >
                              {isSelected && <svg className="w-3 h-3 fill-current" viewBox="0 0 20 20"><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>}
                          </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900 dark:text-white" onClick={(e) => {e.stopPropagation(); navigateTo('ITEM_DETAIL', { itemId: item.id, from: 'JOB_DETAIL', jobId: job.id })}}>
                          <span className="hover:text-sky-500 hover:underline decoration-sky-500 underline-offset-4">{item.name}</span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500 dark:text-slate-400">{item.category}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500 dark:text-slate-400">{item.storageCase || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                          <span className={`px-2 inline-flex text-xs leading-5 font-bold rounded-full ${item.status === ItemStatus.AVAILABLE ? 'bg-green-500/20 text-green-600 dark:text-green-400' : 'bg-red-500/20 text-red-600 dark:text-red-400'}`}>
                              {item.status === ItemStatus.CHECKED_OUT ? 'UNAVAILABLE' : item.status}
                          </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                          {checkedOutTo ? (
                              <span className="font-bold text-red-600 dark:text-red-400 flex items-center gap-1">
                                  <UserIcon size={14} /> {checkedOutTo}
                              </span>
                          ) : (
                              <span className="text-slate-300 dark:text-slate-600">—</span>
                          )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500 dark:text-slate-400">{item.condition}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* ACTIVITY LOG (Signatures & Transactions) */}
        <div className="bg-white dark:bg-slate-800 rounded-lg p-6 shadow-lg border border-slate-200 dark:border-slate-700">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">Activity Log</h3>
            <div className="space-y-4">
                {jobTransactions.length > 0 ? (
                    jobTransactions.map(tx => {
                        const user = findUser(tx.userId);
                        // Prefer the free-text name, fall back to user lookup by ID
                        const assignedToName = tx.assignedToName || (tx.assignedToId ? findUser(tx.assignedToId)?.name : null);
                        const isCheckout = tx.type === TransactionType.CHECKOUT;

                        return (
                            <div key={tx.id} className="border-l-4 border-slate-200 dark:border-slate-700 pl-4 py-1 relative">
                                <div className={`absolute -left-[9px] top-1.5 w-4 h-4 rounded-full border-2 border-white dark:border-slate-800 ${isCheckout ? 'bg-amber-500' : 'bg-green-500'}`}></div>

                                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2">
                                    <div>
                                        <p className="font-bold text-slate-900 dark:text-white flex items-center gap-2">
                                            {isCheckout ? 'Gear Checked Out' : 'Gear Returned'}
                                            <span className="text-xs font-normal text-slate-500 dark:text-slate-400 flex items-center gap-1">
                                                <Clock size={12}/> {new Date(tx.timestamp).toLocaleString()}
                                            </span>
                                        </p>
                                        <div className="text-sm text-slate-600 dark:text-slate-300 mt-1 space-y-1">
                                            <p>Operator: <strong>{user?.name || 'Unknown'}</strong></p>
                                            {assignedToName && (
                                                <p className="flex items-center gap-1 text-red-600 dark:text-red-400 font-semibold">
                                                    <UserIcon size={14}/> <strong>{assignedToName}</strong>
                                                </p>
                                            )}
                                            <p className="text-slate-500 dark:text-slate-400 text-xs mt-1">
                                                {tx.items.length} items processed
                                            </p>
                                        </div>
                                    </div>

                                    {tx.signature && (
                                        <button
                                            onClick={() => setViewSignature(tx.signature || null)}
                                            className="flex items-center gap-2 text-xs font-bold bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-white px-3 py-2 rounded-lg transition-colors border border-slate-200 dark:border-slate-600"
                                        >
                                            <FileSignature size={14} />
                                            View Signature
                                        </button>
                                    )}
                                </div>
                            </div>
                        );
                    })
                ) : (
                    <p className="text-slate-500 dark:text-slate-400 italic">No activity recorded yet.</p>
                )}
            </div>
        </div>

        {/* EXPENSES SECTION */}
        <div className="bg-white dark:bg-slate-800 rounded-lg p-6 shadow-lg border border-slate-200 dark:border-slate-700">
            <div className="flex justify-between items-center mb-4">
                <h3 className="text-xl font-semibold text-slate-900 dark:text-white flex items-center gap-2">
                    <Receipt size={20} className="text-emerald-500" />
                    Expenses ({jobReceipts.length})
                    {totalExpenses > 0 && (
                        <span className="text-sm font-normal text-slate-500 ml-2">
                            ${totalExpenses.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </span>
                    )}
                </h3>
                <button
                    onClick={() => navigateTo('ADD_RECEIPT', { jobId: job.id })}
                    className="text-sm font-medium text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 flex items-center gap-1 px-3 py-1.5 rounded-lg hover:bg-emerald-50 dark:hover:bg-emerald-900/20 transition-colors"
                >
                    <Plus size={16}/> Add Receipt
                </button>
            </div>

            {jobReceipts.length > 0 ? (
                <div className="space-y-3">
                    {jobReceipts.map(receipt => {
                        const receiptUser = findUser(receipt.user_id);
                        return (
                            <div
                                key={receipt.id}
                                onClick={() => navigateTo('ADD_RECEIPT', { receiptId: receipt.id })}
                                className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-900/50 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700/50 cursor-pointer transition-colors group"
                            >
                                <div className="flex items-center gap-3">
                                    {receipt.receipt_image_url ? (
                                        <img src={receipt.receipt_image_url} alt="Receipt" className="w-12 h-12 object-cover rounded" />
                                    ) : (
                                        <div className="w-12 h-12 bg-slate-200 dark:bg-slate-700 rounded flex items-center justify-center">
                                            <FileText className="text-slate-400" size={20} />
                                        </div>
                                    )}
                                    <div>
                                        <p className="font-medium text-slate-900 dark:text-white group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors">{receipt.description}</p>
                                        <p className="text-xs text-slate-500">
                                            {receipt.vendor_name && `${receipt.vendor_name} · `}
                                            {receipt.category} · {receiptUser?.name || 'Unknown'}
                                        </p>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <p className="font-bold text-emerald-600 dark:text-emerald-400">
                                        ${receipt.amount.toFixed(2)}
                                    </p>
                                    <p className="text-xs text-slate-500">{new Date(receipt.expense_date).toLocaleDateString()}</p>
                                </div>
                            </div>
                        );
                    })}

                    {/* Total Row */}
                    <div className="flex items-center justify-between pt-3 mt-3 border-t border-slate-200 dark:border-slate-700">
                        <span className="font-semibold text-slate-700 dark:text-slate-300">Total Expenses</span>
                        <span className="font-bold text-lg text-emerald-600 dark:text-emerald-400">
                            ${totalExpenses.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </span>
                    </div>
                </div>
            ) : (
                <div className="text-center py-8">
                    <DollarSign size={32} className="text-slate-300 dark:text-slate-600 mx-auto mb-2" />
                    <p className="text-slate-500 dark:text-slate-400 italic mb-2">No expenses recorded for this {t.job.toLowerCase()}.</p>
                    <button
                        onClick={() => navigateTo('ADD_RECEIPT', { jobId: job.id })}
                        className="text-emerald-600 dark:text-emerald-400 font-medium hover:underline"
                    >
                        Add the first receipt
                    </button>
                </div>
            )}
        </div>

      </div>
    </div>
  );
};

export default JobDetailScreen;
