
import React, { useState, useEffect } from 'react';
import { useAppContext } from '../context/AppContext';
import { ArrowLeft, Save, X, Package, Plus, Database, Copy, Check, Search, QrCode, Weight } from 'lucide-react';

const REQUIRED_SQL = `
create table if not exists kits (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists kit_items (
  id bigint generated by default as identity primary key,
  kit_id bigint references kits(id) on delete cascade,
  item_id bigint references inventory(id) on delete cascade
);

alter table kits disable row level security;
alter table kit_items disable row level security;
`;

const PackageFormScreen: React.FC<{ kitId?: number }> = ({ kitId }) => {
    const { state, dispatch, navigateTo, supabase, refreshData } = useAppContext();
    
    // Safety: Ensure kitId is a number if passed (handles potential string params)
    const safeKitId = kitId ? Number(kitId) : undefined;
    const isEditing = !!safeKitId;
    const existingKit = safeKitId ? state.kits.find(k => k.id === safeKitId) : undefined;

    const [name, setName] = useState('');
    const [selectedItemIds, setSelectedItemIds] = useState<number[]>([]);
    const [isSaving, setIsSaving] = useState(false);
    
    // Search State
    const [searchTerm, setSearchTerm] = useState('');
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    
    // Error Handling State
    const [showSqlModal, setShowSqlModal] = useState(false);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        if (isEditing && existingKit) {
            setName(existingKit.name);
            setSelectedItemIds(existingKit.itemIds);
        }
    }, [isEditing, existingKit]);

    // Calculate Total Weight
    const totalWeight = selectedItemIds.reduce((sum, id) => {
        const item = state.inventory.find(i => i.id === id);
        return sum + (item?.weight || 0);
    }, 0);

    // Filter items based on search term and exclude already selected items
    const filteredItems = state.inventory.filter(item => {
        const isAlreadySelected = selectedItemIds.includes(item.id);
        if (isAlreadySelected) return false;

        if (!searchTerm) return true;

        const searchLower = searchTerm.toLowerCase();
        return (
            item.name.toLowerCase().includes(searchLower) ||
            item.category.toLowerCase().includes(searchLower) ||
            (item.qrCode && item.qrCode.toLowerCase().includes(searchLower))
        );
    });

    const handleAddItem = (itemId: number) => {
        if (!selectedItemIds.includes(itemId)) {
            setSelectedItemIds(prev => [...prev, itemId]);
            setSearchTerm(''); // Clear search after adding
            // Keep dropdown open for rapid entry, or close? Let's keep it open but focus input.
            const input = document.getElementById('item-search-input');
            if (input) input.focus();
        }
    };

    const handleRemoveItem = (itemId: number) => {
        setSelectedItemIds(prev => prev.filter(id => id !== itemId));
    };

    const copySql = () => {
        navigator.clipboard.writeText(REQUIRED_SQL);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!name.trim()) return alert('Please name the package.');
        if (selectedItemIds.length === 0) return alert('Please add at least one item.');

        setIsSaving(true);

        try {
            let activeKitId = safeKitId;

            if (isEditing && safeKitId) {
                // Update Name
                const { error: updateError } = await supabase.from('kits').update({ name }).eq('id', safeKitId);
                if (updateError) throw updateError;
                
                // Clear items to replace
                const { error: deleteError } = await supabase.from('kit_items').delete().eq('kit_id', safeKitId);
                if (deleteError) throw deleteError;
            } else {
                // Create Kit
                const { data, error } = await supabase.from('kits').insert({ name }).select().single();
                
                if (error) {
                    // Check for Missing Table (42P01) OR Schema Cache error
                    if (error.code === '42P01' || error.message.includes('Could not find the table')) {
                        setShowSqlModal(true);
                        setIsSaving(false);
                        return;
                    }
                    throw error;
                }
                
                if (!data) throw new Error("Database insert failed - no data returned.");
                activeKitId = data.id;
            }

            if (activeKitId) {
                const itemsPayload = selectedItemIds.map(id => ({
                    kit_id: activeKitId,
                    item_id: id
                }));
                
                if (itemsPayload.length > 0) {
                    const { error: itemsError } = await supabase.from('kit_items').insert(itemsPayload);
                    if (itemsError) {
                        if (itemsError.code === '23503') {
                            throw new Error("DATA SYNC ERROR: Some selected items don't exist in the database. Please save items to Inventory first.");
                        }
                        throw itemsError;
                    }
                }
            }

            await refreshData();
            navigateTo('PACKAGES');
        } catch (error: any) {
            console.error("Package Save Error:", error);
            const message = error.message || "Unknown error occurred";
            alert(`Error: ${message}`);
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <div className="max-w-3xl mx-auto pb-20">
            
            {/* DATABASE SETUP MODAL */}
            {showSqlModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in">
                    <div className="bg-white dark:bg-slate-800 w-full max-w-2xl rounded-lg shadow-2xl border border-slate-200 dark:border-slate-700 flex flex-col max-h-[90vh]">
                        <div className="p-6 border-b border-slate-200 dark:border-slate-700 flex items-center gap-3">
                            <div className="p-3 bg-amber-100 dark:bg-amber-900/30 rounded-full text-amber-600 dark:text-amber-400">
                                <Database size={24} />
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-slate-900 dark:text-white">Database Setup Required</h3>
                                <p className="text-sm text-slate-500 dark:text-slate-400">You need to create the "Kits" tables in Supabase.</p>
                            </div>
                        </div>
                        
                        <div className="p-6 overflow-y-auto flex-grow">
                            <p className="text-slate-700 dark:text-slate-300 mb-4">
                                Go to your <strong>Supabase Dashboard</strong> &gt; <strong>SQL Editor</strong> and run the following code:
                            </p>
                            
                            <div className="relative">
                                <pre className="bg-slate-900 text-slate-200 p-4 rounded-lg text-sm font-mono overflow-x-auto whitespace-pre-wrap border border-slate-700">
                                    {REQUIRED_SQL}
                                </pre>
                                <button 
                                    onClick={copySql}
                                    className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white p-2 rounded transition-colors border border-white/20"
                                    title="Copy to Clipboard"
                                >
                                    {copied ? <Check size={16} className="text-green-400"/> : <Copy size={16} />}
                                </button>
                            </div>
                        </div>

                        <div className="p-6 border-t border-slate-200 dark:border-slate-700 flex justify-end gap-3 bg-slate-50 dark:bg-slate-900/50 rounded-b-lg">
                            <button 
                                onClick={() => setShowSqlModal(false)}
                                className="px-6 py-2 bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-800 dark:text-white font-bold rounded-lg transition-colors"
                            >
                                I'll do this later
                            </button>
                            <button 
                                onClick={() => {
                                    setShowSqlModal(false);
                                    // Optionally retry?
                                }}
                                className="px-6 py-2 bg-sky-500 hover:bg-sky-600 text-white font-bold rounded-lg transition-colors"
                            >
                                Done
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <div className="flex justify-between items-center mb-6">
                <button 
                    onClick={() => navigateTo('PACKAGES')}
                    className="flex items-center gap-2 text-sm text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300 transition-colors font-semibold"
                >
                    <ArrowLeft size={16} />
                    Cancel
                </button>
            </div>

            <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">{isEditing ? 'Edit Package' : 'Create New Package'}</h2>

            <form onSubmit={handleSubmit} className="space-y-8">
                <div className="bg-white dark:bg-slate-800 rounded-lg shadow-lg p-6 border border-slate-200 dark:border-slate-700">
                    <div className="mb-6">
                        <label className="block text-sm font-medium text-slate-500 dark:text-slate-300 mb-1">Package Name</label>
                        <input 
                            type="text" 
                            required
                            className="w-full bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500 border border-slate-300 dark:border-slate-600 text-lg font-bold"
                            placeholder="e.g., Camera A Kit"
                            value={name}
                            onChange={e => setName(e.target.value)}
                        />
                    </div>

                    <div className="mb-4">
                        <div className="flex justify-between items-center mb-2">
                            <h3 className="text-lg font-semibold text-slate-900 dark:text-white flex items-center gap-2">
                                <Package size={20} /> Included Items
                            </h3>
                            <div className="flex items-center gap-2 bg-slate-100 dark:bg-slate-700 px-3 py-1 rounded-full">
                                <Weight size={16} className="text-slate-500 dark:text-slate-400" />
                                <span className="text-sm font-bold text-slate-700 dark:text-white">
                                    {totalWeight > 0 ? `${totalWeight.toFixed(1)} lbs` : '0 lbs'}
                                </span>
                            </div>
                        </div>
                        
                        <div className="mb-4 relative">
                            <label className="block text-sm font-medium text-slate-500 dark:text-slate-300 mb-1">Add Items</label>
                            
                            {/* Search Input */}
                            <div className="relative">
                                <input
                                    id="item-search-input"
                                    type="text"
                                    className="w-full bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white pl-10 pr-4 py-3 rounded-lg border border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-sky-500"
                                    placeholder="Search by Name, Category, or QR Code..."
                                    value={searchTerm}
                                    onChange={(e) => {
                                        setSearchTerm(e.target.value);
                                        setIsDropdownOpen(true);
                                    }}
                                    onFocus={() => setIsDropdownOpen(true)}
                                    autoComplete="off"
                                />
                                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-500 dark:text-slate-400">
                                    <Search size={18} />
                                </div>
                                {searchTerm && (
                                    <button 
                                        type="button"
                                        onClick={() => setSearchTerm('')}
                                        className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
                                    >
                                        <X size={16} />
                                    </button>
                                )}
                            </div>

                            {/* Dropdown Results */}
                            {isDropdownOpen && (
                                <>
                                    <div className="fixed inset-0 z-10" onClick={() => setIsDropdownOpen(false)}></div>
                                    <div className="absolute z-20 w-full mt-1 bg-white dark:bg-slate-700 rounded-lg shadow-xl border border-slate-200 dark:border-slate-600 max-h-60 overflow-y-auto">
                                        {filteredItems.length > 0 ? (
                                            <ul className="divide-y divide-slate-100 dark:divide-slate-600">
                                                {filteredItems.map(item => (
                                                    <li 
                                                        key={item.id}
                                                        onMouseDown={(e) => {
                                                            e.preventDefault(); // Prevent blur on input
                                                            handleAddItem(item.id);
                                                        }}
                                                        className="px-4 py-3 hover:bg-sky-50 dark:hover:bg-slate-600 cursor-pointer flex justify-between items-center group transition-colors"
                                                    >
                                                        <div>
                                                            <p className="text-slate-900 dark:text-white font-medium">{item.name}</p>
                                                            <div className="flex gap-2 text-xs text-slate-500 dark:text-slate-400">
                                                                <span>{item.category}</span>
                                                                {item.weight && <span>• {item.weight} lbs</span>}
                                                                {item.qrCode && (
                                                                    <span className="flex items-center gap-1 font-mono bg-slate-100 dark:bg-slate-800 px-1 rounded">
                                                                        <QrCode size={10}/> {item.qrCode}
                                                                    </span>
                                                                )}
                                                            </div>
                                                        </div>
                                                        <Plus size={18} className="text-sky-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                                                    </li>
                                                ))}
                                            </ul>
                                        ) : (
                                            <div className="p-4 text-center text-slate-500 dark:text-slate-400">
                                                <p className="text-sm">No matching items found.</p>
                                            </div>
                                        )}
                                    </div>
                                </>
                            )}
                        </div>

                        <div className="space-y-2">
                            {selectedItemIds.length === 0 && <p className="text-slate-500 italic p-4 text-center bg-slate-50 dark:bg-slate-900/30 rounded-lg border border-dashed border-slate-300 dark:border-slate-700">No items in this package yet. Search above to add items.</p>}
                            {selectedItemIds.map(id => {
                                const item = state.inventory.find(i => i.id === id);
                                if (!item) return null;
                                return (
                                    <div key={id} className="flex justify-between items-center bg-slate-50 dark:bg-slate-700/50 p-3 rounded-lg border border-slate-200 dark:border-slate-700 animate-in slide-in-from-top-1 duration-200">
                                        <div>
                                            <p className="text-slate-900 dark:text-white font-medium">{item.name}</p>
                                            <div className="flex gap-3 text-xs text-slate-500 dark:text-slate-400">
                                                <span>{item.category}</span>
                                                {item.weight && <span>{item.weight} lbs</span>}
                                            </div>
                                        </div>
                                        <button 
                                            type="button"
                                            onClick={() => handleRemoveItem(id)}
                                            className="text-slate-400 hover:text-red-500 dark:hover:text-red-400 p-2 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-full transition-colors"
                                            title="Remove item"
                                        >
                                            <X size={18} />
                                        </button>
                                    </div>
                                )
                            })}
                        </div>
                    </div>
                </div>

                <div className="flex justify-end">
                    <button 
                        type="submit" 
                        disabled={isSaving}
                        className="flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white font-bold py-3 px-8 rounded-lg transition-colors shadow-lg disabled:opacity-50"
                    >
                        <Save size={20} />
                        {isSaving ? 'Saving...' : (isEditing ? 'Update Package' : 'Create Package')}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default PackageFormScreen;
